---

- name: configure runner
  shell: |
    gitlab-runner register \
      --non-interactive \
      --url "HTTPS://{{ args_gitlab_url }}" \
      --registration-token "{{ args_gitlab_runnertoken }}" \
      --description "ALEX Gitlab runner" \
      --executor "shell"
  args:
    executable: /bin/bash

- name: configure docker group membership
  shell: |
    #echo "Test"
    if ( id -nG gitlab-runner | grep -qw "docker" ) ; then 
      echo "member"
    else
      echo "not member"
      usermod -a -G docker gitlab-runner
    fi
  args:
    executable: /bin/bash
  register: result
  changed_when: '"not member" in result.stdout'

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /home/gitlab-runner/.docker
    state: directory
    owner: gitlab-runner
    group: gitlab-runner
    mode: '0755'

- name: Copy docker config file
  ansible.builtin.template:
    src: "config.json.j2"
    dest: "/home/gitlab-runner/.docker/config.json"
    owner: gitlab-runner
    group: gitlab-runner
    mode: 0666
