---

- name: configure runner
  shell: |
    gitlab-runner register \
      --non-interactive \
      --url "HTTPS://{{ args_gitlab_url }}" \
      --registration-token "{{ args_gitlab_runnertoken }}" \
      --description "ALEX Gitlab runner" \
      --executor "shell"
  args:
    executable: /bin/bash

- name: configure docker group membership
  shell: |
    #echo "Test"
    if ( id -nG gitlab-runner | grep -qw "docker" ) ; then 
      echo "member"
    else
      echo "not member"
      usermod -a -G docker gitlab-runner
    fi
  args:
    executable: /bin/bash
  register: result
  changed_when: '"not member" in result.stdout'
